language: node_js
dist: focal
sudo: required
node_js: stable
install:
  - npm install
script:
  - npm run build
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
